### ISSUE TITLE
Reset with given state?

### ISSUE THREAD

**Issue by fritx** [wwayne/redux-reset#1]
Hello, do you mind adding support for this?
https://github.com/reactjs/redux/pull/658#issuecomment-136478950

``` js
function makeHydratable(reducer, hydrateActionType) {
  return function (state, action) {
    switch (action.type) {
    case hydrateActionType:
      return reducer(action.state, action);
    default:
      return reducer(state, action);
    } 
  }
}

// later
store.dispatch({
  type: HYDRATE_STATE,
  state: initialState
});
```

---

Woo, but the way, just figured out you are in wiredcraft!
[The Wiredcraft Blog](https://wiredcraft.com/blog/) is incredibly awesome :+1:

**Comment by wwayne** [comment]
@fritx I just updated the component to `0.2.0`, you can give Redux a new initial state after reset, related doc is available here: https://github.com/wwayne/redux-reset#reset-and-specific-to-a-new-initial-state

**Comment by fritx** [comment]
Thanks! Will try it in project soon!
