### ISSUE TITLE
Is there a way to add an exception to what will be reset?

### ISSUE THREAD

**Issue by ghost** [wwayne/redux-reset#3]
Ie. resetRedux(exception(state.config.dontResetThisVal))

Basically I have a config var in the store I dont want to ever reset.

**Comment by wwayne** [comment]
@msmfsd No for the moment, but I think you can pass those values into action when doing reset https://github.com/wwayne/redux-reset#reset-and-specific-to-a-new-initial-state-new-state-comes-from-a-specific-params-in-action, it's kind of resetting some specific state to its previous value when resetting all state

**Comment by ghost** [comment]
Thats ok I ended up just setting an initial state on the reducer and that gets re-hydrated on reset.
