### ISSUE TITLE
Exclude certain keys from state with reduxReset

### ISSUE THREAD

**Issue by Andrea-Arguello** [wwayne/redux-reset#8]
I am implementing a logout in a project, where I want to keep a certain key from the state from resetting after calling reduxReset. I am also using redux-persist, which I've heard causes some trouble.

The key is "netInfo," where internet connection is evaluated and saved. After reduxReset, this variable becomes undefined. Only after closing and re-opening the app does this issue get fixed.

**Comment by wwayne** [comment]
Hi, would this helpful [Reset and specific to a new initial state, new state comes from a specific params in action](https://github.com/wwayne/redux-reset#reset-and-specific-to-a-new-initial-state-new-state-comes-from-a-specific-params-in-action)
